import random
num1 = random.randrange(1, 100)
num2 = random.randrange(1, 100)
print()
print("Two random number values")
print(f"Number 1: {num1} | Number 2: {num2}")
print(f"Addition:\t\t{num1 + num2}")
print(f"Subtraction:\t\t{num1 - num2}")
print(f"Multiplication:\t\t{num1 * num2}")
print(f"Division:\t\t{num1 / num2}")
print(f"Remainder:\t\t{num1 % num2}")
print(f"Floor:\t\t\t{num1 // num2}")
print()
NUMBER2 = 25
num2 = NUMBER2
print("One random number value and one constant value")
print(f"Number 1: {num1} | Number 2: {num2}")
print(f"Addition:\t\t{num1 + num2}")
print(f"Subtraction:\t\t{num1 - num2}")
print(f"Multiplication:\t\t{num1 * num2}")
print(f"Division:\t\t{num1 / num2}")
print(f"Remainder:\t\t{num1 % num2}")
print(f"Floor:\t\t\t{num1 // num2}")
print()